<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DepartmentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('departments')->insert([
            ['id' => 1, 'name' => '01 Ain'],
            ['id' => 2, 'name' => '02 Aisne'],
            ['id' => 3, 'name' => '03 Allier'],
            ['id' => 4, 'name' => '04 Alpes-de-Haute-Provence'],
            ['id' => 5, 'name' => '05 Hautes-Alpes'],
            ['id' => 6, 'name' => '06 Alpes-Maritimes'],
            ['id' => 7, 'name' => '07 Ardèche'],
            ['id' => 8, 'name' => '08 Ardennes'],
            ['id' => 9, 'name' => '09 Ariège'],
            ['id' => 10, 'name' => '10 Aube'],
            ['id' => 11, 'name' => '11 Aude'],
            ['id' => 12, 'name' => '12 Aveyron'],
            ['id' => 13, 'name' => '13 Bouches-du-Rhône'],
            ['id' => 14, 'name' => '14 Calvados'],
            ['id' => 15, 'name' => '15 Cantal'],
            ['id' => 16, 'name' => '16 Charente'],
            ['id' => 17, 'name' => '17 Charente-Maritime'],
            ['id' => 18, 'name' => '18 Cher'],
            ['id' => 19, 'name' => '19 Corrèze'],
            ['id' => 20, 'name' => '2a Corse-du-sud'],
            ['id' => 21, 'name' => '2b Haute-corse'],
            ['id' => 22, 'name' => '21 Côte-d\'or'],
            ['id' => 23, 'name' => '22 Côtes-d\'armor'],
            ['id' => 24, 'name' => '23 Creuse'],
            ['id' => 25, 'name' => '24 Dordogne'],
            ['id' => 26, 'name' => '25 Doubs'],
            ['id' => 27, 'name' => '26 Drôme'],
            ['id' => 28, 'name' => '27 Eure'],
            ['id' => 29, 'name' => '28 Eure-et-Loir'],
            ['id' => 30, 'name' => '29 Finistère'],
            ['id' => 31, 'name' => '30 Gard'],
            ['id' => 32, 'name' => '31 Haute-Garonne'],
            ['id' => 33, 'name' => '32 Gers'],
            ['id' => 34, 'name' => '33 Gironde'],
            ['id' => 35, 'name' => '34 Hérault'],
            ['id' => 36, 'name' => '35 Ile-et-Vilaine'],
            ['id' => 37, 'name' => '36 Indre'],
            ['id' => 38, 'name' => '37 Indre-et-Loire'],
            ['id' => 39, 'name' => '38 Isère'],
            ['id' => 40, 'name' => '39 Jura'],
            ['id' => 41, 'name' => '40 Landes'],
            ['id' => 42, 'name' => '41 Loir-et-Cher'],
            ['id' => 43, 'name' => '42 Loire'],
            ['id' => 44, 'name' => '43 Haute-Loire'],
            ['id' => 45, 'name' => '44 Loire-Atlantique'],
            ['id' => 46, 'name' => '45 Loiret'],
            ['id' => 47, 'name' => '46 Lot'],
            ['id' => 48, 'name' => '47 Lot-et-Garonne'],
            ['id' => 49, 'name' => '48 Lozère'],
            ['id' => 50, 'name' => '49 Maine-et-Loire'],
            ['id' => 51, 'name' => '50 Manche'],
            ['id' => 52, 'name' => '51 Marne'],
            ['id' => 53, 'name' => '52 Haute-Marne'],
            ['id' => 54, 'name' => '53 Mayenne'],
            ['id' => 55, 'name' => '54 Meurthe-et-Moselle'],
            ['id' => 56, 'name' => '55 Meuse'],
            ['id' => 57, 'name' => '56 Morbihan'],
            ['id' => 58, 'name' => '57 Moselle'],
            ['id' => 59, 'name' => '58 Nièvre'],
            ['id' => 60, 'name' => '59 Nord'],
            ['id' => 61, 'name' => '60 Oise'],
            ['id' => 62, 'name' => '61 Orne'],
            ['id' => 63, 'name' => '62 Pas-de-Calais'],
            ['id' => 64, 'name' => '63 Puy-de-Dôme'],
            ['id' => 65, 'name' => '64 Pyrénées-Atlantiques'],
            ['id' => 66, 'name' => '65 Hautes-Pyrénées'],
            ['id' => 67, 'name' => '66 Pyrénées-Orientales'],
            ['id' => 68, 'name' => '67 Bas-Rhin'],
            ['id' => 69, 'name' => '68 Haut-Rhin'],
            ['id' => 70, 'name' => '69 Rhône'],
            ['id' => 71, 'name' => '70 Haute-Saône'],
            ['id' => 72, 'name' => '71 Saône-et-Loire'],
            ['id' => 73, 'name' => '72 Sarthe'],
            ['id' => 74, 'name' => '73 Savoie'],
            ['id' => 75, 'name' => '74 Haute-Savoie'],
            ['id' => 76, 'name' => '75 Paris'],
            ['id' => 77, 'name' => '76 Seine-Maritime'],
            ['id' => 78, 'name' => '77 Seine-et-Marne'],
            ['id' => 79, 'name' => '78 Yvelines'],
            ['id' => 80, 'name' => '79 Deux-Sèvres'],
            ['id' => 81, 'name' => '80 Somme'],
            ['id' => 82, 'name' => '81 Tarn'],
            ['id' => 83, 'name' => '82 Tarn-et-Garonne'],
            ['id' => 84, 'name' => '83 Var'],
            ['id' => 85, 'name' => '84 Vaucluse'],
            ['id' => 86, 'name' => '85 Vendée'],
            ['id' => 87, 'name' => '86 Vienne'],
            ['id' => 88, 'name' => '87 Haute-Vienne'],
            ['id' => 89, 'name' => '88 Vosges'],
            ['id' => 90, 'name' => '89 Yonne'],
            ['id' => 91, 'name' => '90 Territoire de Belfort'],
            ['id' => 92, 'name' => '91 Essonne'],
            ['id' => 93, 'name' => '92 Hauts-de-Seine'],
            ['id' => 94, 'name' => '93 Seine-Saint-Denis'],
            ['id' => 95, 'name' => '94 Val-de-Marne'],
            ['id' => 96, 'name' => '95 Val-d\'Oise']
        ]);
    }
}
